[package]
name = "bluper"
version = "0.1.0"
edition = "2024"

[dependencies]
ble-peripheral-rust = { git = "https://github.com/Tiggilyboo/ble-peripheral-rust" }
anyhow = "1.0"
tokio = "1.48"
uuid = "1.18"
winit = "0.30"
softbuffer = "0.4"
